services:
  app:
    build: ./
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    stdin_open: true
    tty: true
    user: 1000:1000